repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: regen-test-levels
        name: Regen test levels
        language: system
        entry: uv run python -m minigolf.game.levels tests/level1.json
        pass_filenames: false
