name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev --locked

      - name: Lint and format
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Run tests with coverage
        run: uv run pytest --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
